name: react-express-emavra
services:
  frontend:
    container_name: frontend-dev
    build:
      context: ./front
    restart: always
    networks:
      - emavradev-net
    ports:
      - 81:90
  backend:
    container_name: backend-dev
    build:
      context: ./back
    ports:
      - 82:3000
    restart: always
    command: >
      sh -c "npx prisma db push  && npm start "
    networks:
      - emavradev-net
    volumes:
      - ./back/:/code
networks:
  emavradev-net:
    driver: bridge
