name: react-express-emavra
services:
  frontend:
    container_name: frontend-dev
    build:
      context: ./front      
    restart: always
    networks:
      - emavradev-net
    ports:
      - 81:5173
  backend:
    container_name: backend-dev
    build:
      context: ./back
    ports:
      - 82:8000
    restart: always
    command: >
      sh -c "npx prisma db push && npx prisma migrate dev && npm start "
    networks:
      - emavradev-net
    volumes:
      - ./back/:/code
      - /code/node_modules
networks:
  emavradev-net:
    driver: bridge